services:
  db:
    container_name: qso_db
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_DB=qso_logger
      - POSTGRES_USER=qso_user
      - POSTGRES_PASSWORD=qso_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - qso_net

  web:
    container_name: qso_web
    build: .
    restart: always
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - DJANGO_SETTINGS_MODULE=QSOPlan.settings
      - POSTGRES_DB=qso_logger
      - POSTGRES_USER=qso_user
      - POSTGRES_PASSWORD=qso_password
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - CORS_ALLOWED_ORIGINS=http://localhost:3000,http://127.0.0.1:3000
    volumes:
      - .:/app
    depends_on:
      - db
    command: >
      bash -c "python manage.py wait_for_db &&
               python manage.py migrate &&
               python manage.py runserver 0.0.0.0:8000"
    networks:
      - qso_net

  frontend:
    container_name: qso_frontend
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    networks:
      - qso_net
    depends_on:
      - web

networks:
  qso_net:
    driver: bridge

volumes:
  postgres_data:
