# Generated by Django 5.0.1 on 2025-02-10 21:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qso_logger', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qsocontact',
            name='confirmed',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='qsocontact',
            name='datetime',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='qsocontact',
            name='initiator_location',
            field=models.CharField(max_length=6, validators=[django.core.validators.RegexValidator('^[A-Z0-9]{6}$', 'Grid square must be exactly 6 characters')]),
        ),
        migrations.AlterField(
            model_name='qsocontact',
            name='recipient',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^[A-Z0-9]{3,10}$', 'Call sign must be 3-10 alphanumeric characters')]),
        ),
        migrations.AlterField(
            model_name='qsocontact',
            name='recipient_location',
            field=models.CharField(max_length=6, validators=[django.core.validators.RegexValidator('^[A-Z0-9]{6}$', 'Grid square must be exactly 6 characters')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='default_grid_square',
            field=models.CharField(blank=True, max_length=6, validators=[django.core.validators.RegexValidator('^[A-Z0-9]{6}$', 'Grid square must be exactly 6 characters')]),
        ),
        migrations.AddIndex(
            model_name='qsocontact',
            index=models.Index(fields=['recipient', 'datetime'], name='qso_logger__recipie_1ec8db_idx'),
        ),
        migrations.AddIndex(
            model_name='qsocontact',
            index=models.Index(fields=['initiator', 'recipient', 'datetime'], name='qso_logger__initiat_0ffe89_idx'),
        ),
        migrations.AddIndex(
            model_name='qsocontact',
            index=models.Index(fields=['frequency', 'mode', 'datetime'], name='qso_logger__frequen_a6cda2_idx'),
        ),
    ]
