# Generated by Django 5.0.1 on 2025-02-10 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qso_logger', '0003_alter_qsocontact_initiator_location_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='qsocontact',
            options={'verbose_name': 'QSO Contact', 'verbose_name_plural': 'QSO Contacts'},
        ),
    ]
